# Generated by Django 2.0.6 on 2018-08-17 05:42

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetTrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='preset training')),
                ('instructions', models.TextField()),
                ('time', models.IntegerField(default=30)),
                ('reps', models.IntegerField(default=10)),
                ('modules', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('is_random', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(choices=[(30, '30'), (45, '45'), (60, '60'), (75, '75'), (90, '90'), (105, '105'), (120, '120')], default=30)),
                ('reps', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(10)])),
                ('modules', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1)),
                ('is_random', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('results', django.contrib.postgres.fields.jsonb.JSONField()),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.TrainingDescription')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
