# Generated by Django 2.0.6 on 2018-08-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presettrainingsession',
            name='type_of_measure',
        ),
        migrations.RemoveField(
            model_name='trainingdescription',
            name='type_of_measure',
        ),
        migrations.AddField(
            model_name='presettrainingsession',
            name='typeReaction',
            field=models.CharField(choices=[('SIMPLE', 'Simple'), ('COMPLEJO', 'Complejo')], default='SIMPLE', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingdescription',
            name='typeReaction',
            field=models.CharField(choices=[('SIMPLE', 'Simple'), ('COMPLEJO', 'Complejo')], default='SIMPLE', max_length=10),
        ),
        migrations.DeleteModel(
            name='TypeReactionTime',
        ),
    ]
