# Generated by Django 2.0.6 on 2018-08-19 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20180816_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdescription',
            name='reps',
            field=models.IntegerField(default=10, validators=[django.core.validators.DecimalValidator(decimal_places=1, max_digits=2), django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(10)]),
        ),
    ]
