# Generated by Django 2.0.6 on 2019-01-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_colorstimuli'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturesession',
            name='time_activation',
            field=models.IntegerField(default=1),
        ),
    ]
