# Generated by Django 2.0.6 on 2018-08-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_trainingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='presettrainingsession',
            name='instructions',
            field=models.TextField(default='Instrucciones en desarrollo'),
            preserve_default=False,
        ),
    ]
