# Generated by Django 2.0.6 on 2018-08-15 17:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0005_presettrainingsession_instructions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presettrainingsession',
            old_name='type',
            new_name='training_type',
        ),
        migrations.RenameField(
            model_name='trainingdescription',
            old_name='type',
            new_name='training_type',
        ),
        migrations.RemoveField(
            model_name='presettrainingsession',
            name='key',
        ),
        migrations.RemoveField(
            model_name='trainingtype',
            name='key',
        ),
        migrations.AddField(
            model_name='presettrainingsession',
            name='is_random',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presettrainingsession',
            name='name',
            field=models.TextField(default='preset training'),
        ),
        migrations.AddField(
            model_name='presettrainingsession',
            name='reps',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='presettrainingsession',
            name='time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='trainingdescription',
            name='is_random',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingdescription',
            name='reps',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='trainingdescription',
            name='time',
            field=models.IntegerField(choices=[(30, 30), (45, 45), (60, 60), (75, 75), (90, 90), (105, 105), (120, 120)], default=30),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='type_training',
            field=models.CharField(choices=[('Secuencial', 'Secuencial'), ('Aleatorio', 'Aleatorio')], default='Secuencial', max_length=30),
        ),
        migrations.AlterField(
            model_name='presettrainingsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainingdescription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainingdescription',
            name='name',
            field=models.TextField(default='SOME NAME'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainingtype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
