# Generated by Django 2.0.6 on 2018-08-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20180815_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presettrainingsession',
            name='is_random',
        ),
        migrations.RemoveField(
            model_name='trainingdescription',
            name='is_random',
        ),
    ]
